import logging
# logging.basicConfig(level=logging.INFO,format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
# logger = logging.getLogger(__name__)
#
# logger.info('start print log')
# logger.debug('test debug log')
# logger.warning('test warning log')
# logger.info('end print log')
logger = logging.getLogger(__name__)
logger.setLevel(level=logging.INFO)
hander = logging.FileHandler('test.log')
hander.setLevel(logging.INFO)
format = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
hander.setFormatter(format)
logger.addHandler(hander)
logger.info('start print log')
logger.debug('test debug log')
logger.warning('test warning log')
logger.info('end print log')
